#!/bin/bash
#+
# Run GNU autotools stuff preparatory to building from the source tree.
#
# Execute this script with the working directory set to the top of
# the dvdauthor source tree, and it will create the configure scripts
# and other related bits and pieces.
#
# You would think "autoreconf -i" on its own would be enough, but
# unfortunately that assumes that a program using iconv also needs
# gettext as well, which is not true for DVDAuthor. So the autoreconf
# reports an error that config.rpath does not exist, which is why it
# has to be explicitly copied below.
#
# Created by Lawrence D'Oliveiro <ldo@geek-central.gen.nz>.
#-
mkdir autotools
cp /usr/share/gettext/config.rpath autotools/
autoreconf -i

